apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: spring-reactor
build:
  artifacts:
  - image: sriramsundhar/spring-reactor
    jib: {}
deploy:
  kubectl:
    manifests:
    - k8s/local.yml

portForward:
  - resourceType: pod
    resourceName: spring-reactor
    port: 8080
